// ════════════════════════════════════════════════════════════════════════
// 我的自評 —— 這一層是「我」，不是框架。別人 clone 框架時不會拿到這個檔。
//
// key 對應 framework/competencies.js 的 ITEMS[].id。
//
//   status    have / partial / learning / need / wont
//   reason    wont 必填：為什麼刻意不學。這份 scope cut 清單本身就是給面試官看的東西
//   social    社創／LFT 背景的可轉移程度（high / mid / low）
//   note      我自己的備註
//   evidence  過了 rubric 的產出物路徑。空陣列 = 還沒有佐證，**不要因為覺得會了就填**
//
// ⚠️ 2026-08-19 從 ROADMAP_DATA + SKILLS_DATA 搬出來，每一項狀態都是**原封搬移**，
//    遷移腳本不發明任何判斷。原本同一個概念在兩份資料裡各有一份 status；
//    現在只有這裡一份，兩個視圖都讀它。
//
// ⚠️ 傳統 <script src>，不可改成 type="module"。
// ════════════════════════════════════════════════════════════════════════

const ASSESSMENT = {
  "what-is-product-management": { status: "have" },
  "product-vs-project-management": { status: "partial" },
  "roles-and-responsibilities": { status: "have" },
  "key-skills-overview": { status: "partial" },
  "mind-mapping": { status: "have" },
  "brainstorming": { status: "have" },
  "scamper": { status: "wont", reason: "需要時現查即可，不需預先學。" },
  "problem-framing": { status: "partial" },
  "blue-ocean-strategy": { status: "wont", reason: "層級太高，現在用不到。" },
  "triz": { status: "wont", reason: "算是選修不是必修，優先度低。" },
  "identifying-market-needs": { status: "need" },
  "competitive-analysis": { status: "partial" },
  "emerging-market-trends": { status: "need" },
  "tam-sam-som": { status: "need" },
  "user-personas": { status: "partial" },
  "user-interviews": { status: "need" },
  "surveys-and-questionnaires": { status: "need" },
  "ethnographic-research": { status: "wont", reason: "成本太高，先做 User Interview。" },
  "jobs-to-be-done": { status: "partial", social: "mid", note: "概念理解中" },
  "usability-testing": { status: "need", social: "low", note: "" },
  "usp-positioning": { status: "need" },
  "market-segmentation": { status: "need" },
  "value-proposition-canvas": { status: "need" },
  "business-model-canvas": { status: "need", social: "mid", note: "理解商業邏輯" },
  "porter-s-five-forces": { status: "wont", reason: "概念理解即可，不需深入。", social: "low", note: "概念理解即可" },
  "swot-pestle": { status: "wont", reason: "輸入品質遠比工具本身重要；低頻工具，不值得反覆操練。" },
  "competitive-advantage": { status: "need" },
  "strategic-thinking": { status: "partial" },
  "okrs": { status: "have" },
  "north-star-metric": { status: "partial", social: "low", note: "理解概念，需要實例" },
  "goal-types-and-baselines": { status: "need" },
  "product-vision-statement": { status: "need" },
  "creating-a-roadmap": { status: "partial" },
  "prioritizing-features": { status: "partial" },
  "rice-moscow": { status: "partial" },
  "outcome-based-roadmaps": { status: "need" },
  "communicating-the-roadmap": { status: "need" },
  "writing-prds": { status: "partial" },
  "user-stories": { status: "have" },
  "job-stories": { status: "need" },
  "acceptance-criteria": { status: "have" },
  "backlog-management": { status: "have" },
  "user-story-mapping": { status: "have" },
  "principles-of-ux-design": { status: "have" },
  "wireframing-and-prototyping": { status: "have" },
  "design-thinking": { status: "partial" },
  "service-design": { status: "need", social: "high", note: "長期社創工具：NGO/社企方案設計核心" },
  "interaction-design": { status: "have" },
  "a-b-testing": { status: "need" },
  "scrum": { status: "have" },
  "kanban": { status: "have" },
  "sprint-planning": { status: "have" },
  "daily-standups": { status: "have" },
  "retrospectives": { status: "have" },
  "mvp": { status: "partial" },
  "go-to-market-strategy": { status: "need" },
  "release-strategies": { status: "need" },
  "feature-toggles-dark-launch": { status: "have" },
  "growth-hacking": { status: "wont", reason: "應該拆回基礎能力（funnel、實驗設計、單位經濟），而不是當一顆要不要學的大球。" },
  "dau-mau": { status: "partial" },
  "retention-rate": { status: "need" },
  "churn-rate": { status: "need" },
  "conversion-rate": { status: "need" },
  "ltv-cac": { status: "need" },
  "funnel-analysis": { status: "partial" },
  "cohort-analysis": { status: "need" },
  "ga4-mixpanel": { status: "partial" },
  "sql-for-product": { status: "partial" },
  "active-listening": { status: "have" },
  "conflict-resolution": { status: "have", social: "high", note: "" },
  "alignment-and-buy-in": { status: "have" },
  "difficult-conversations": { status: "partial" },
  "executive-communication": { status: "need", social: "mid", note: "需要練習 C-level 簡報" },
  "jira-gitlab": { status: "have" },
  "notion": { status: "have" },
  "linear": { status: "have" },
  "slack": { status: "have" },
  "figma": { status: "have" },
  "productboard-aha": { status: "need" },
  "amplitude-heap": { status: "need" },
  "miro-figjam": { status: "need" },
  "ai-feature-design": { status: "have" },
  "prompt-engineering": { status: "have" },
  "model-limitation-評估": { status: "have" },
  "ml-in-product-mgmt": { status: "partial" },
  "ai-風險評估": { status: "need" },
  "platform-thinking": { status: "need" },
  "scaling-products": { status: "need" },
  "influencing-without-authority": { status: "need" },
  "emotional-intelligence": { status: "partial" },
  "市場規模評估": { status: "need", social: "low", note: "PDM 面試必考" },
  "競品分析": { status: "partial", social: "low", note: "Phase 1 作業：輸出一份" },
  "okr-設定": { status: "have", social: "mid", note: "Scrum Master 期間用過" },
  "rice-moscow-優先序": { status: "partial", social: "low", note: "理論懂，需要實際帶過一輪" },
  "prd-撰寫": { status: "partial", social: "low", note: "Phase 1 首要任務" },
  "agile-scrum": { status: "have", social: "low", note: "SM 3個月，直接對應" },
  "risk-management": { status: "need", social: "mid", note: "PJM 較重要" },
  "跨部門溝通": { status: "have", social: "high", note: "工程師 + 獵頭背景都有" },
  "stakeholder-alignment": { status: "have", social: "high", note: "SM 期間實戰過" },
  "ga4-分析工具": { status: "partial", social: "low", note: "Phase 1：完成 GA4 認證" },
  "sql": { status: "partial", social: "low", note: "Phase 2：Mode Analytics Tutorial" },
  "funnel-cohort-分析": { status: "need", social: "low", note: "面試必問" },
  "a-b-testing-設計": { status: "need", social: "low", note: "" },
  "user-interview-設計": { status: "need", social: "high", note: "PDM 核心，需補" },
  "problem-definition": { status: "have", social: "high", note: "工程師debug思維直接轉" },
  "mvp-定義": { status: "partial", social: "mid", note: "理論懂，需要輸出案例" },
  "a-b-testing-執行": { status: "need", social: "low", note: "" },
  "假型-測試": { status: "wont", reason: "概念理解就好；真正要練的是「如何問對問題、選對驗證方法」。", social: "low", note: "概念理解就好" },
  "gtm-strategy": { status: "need", social: "low", note: "PJM 較少用，PDM 必要" },
  "value-proposition-設計": { status: "need", social: "mid", note: "" },
  "launch-planning": { status: "need", social: "low", note: "" },
  "api-系統架構溝通": { status: "have", social: "low", note: "最大優勢，直接命中JD" },
  "前端可行性評估": { status: "have", social: "low", note: "" },
  "後端-db-邏輯理解": { status: "have", social: "low", note: "" },
  "figma-讀稿-基礎操作": { status: "have", social: "low", note: "" },
  "rag-知識庫治理": { status: "need", social: "mid", note: "切偵策略、資料新鮮度、權限分層、回答品質評估" },
  "ai-輔助-discovery-的證據紀律": { status: "need", social: "high", note: "區分真實證據與模型推論" },
  "vibe-coding-prototype": { status: "partial", social: "mid", note: "本站與 portfolio 即為產出" },
  "agent-工作流設計": { status: "partial", social: "mid", note: "拆解任務、工具邊界、人工介入點、失敗回復" },
  "why-pm-why-now-why-you-敘事": { status: "need", social: "high", note: "含工程→PM 的能力翻譯；面試必問" },
  "star-故事庫": { status: "need", social: "high", note: "含社創動機與 PM 能力的連結" },
};

// evidence 是另一個 map，刻意分開：狀態是我的判斷（常改），
// 佐證是 rubric 跑出來的事實（只增不改）。混在一起會讓人手改到後者。
const EVIDENCE = {
  // "prd-writing": ["docs/evidence/prd-review-20260914.json"],
};
