// ════════════════════════════════════════════════════════════════════════
// 能力骨架（competency spine）—— 這是框架本體，可以打包給別人 clone。
//
// **這個檔案裡沒有任何一個人的自評。** 誰學到哪裡在 profile/assessment.js，
// 兩者靠 id 對應。分層的判準是擁有權：框架是共用的，自評是你的。
//
// ⚠️ 2026-08-19 由 ROADMAP_DATA（92）+ SKILLS_DATA（39）合併而來，去重後 121 個概念。
//    合併前那兩份**各自帶一份 status，不互相同步**，CLAUDE.md 標為「這個 repo 最容易
//    踩的地方」。現在狀態只存在 assessment 一個地方，兩個視圖都從它衍生——
//    改一次，兩邊一起變。這是這次合併真正買到的東西。
//
// ⚠️ 傳統 <script src>，不可改成 type="module"（ES module 在 file:// 下被 CORS 擋掉）。
// ════════════════════════════════════════════════════════════════════════

const COMPETENCY_AREAS = [
  { id: "product-execution",  name: "Product Execution",  nameZh: "產品執行", definition: "把卓越的產品做出來的能力。" },
  { id: "customer-insight",   name: "Customer Insight",   nameZh: "顧客洞察", definition: "理解並回應顧客需求的能力。" },
  { id: "product-strategy",   name: "Product Strategy",   nameZh: "產品策略", definition: "透過產品驅動商業成果的能力。" },
  { id: "influencing-people", name: "Influencing People", nameZh: "影響他人", definition: "讓人們聚集在團隊工作周圍的能力。" },
];

// 來源代號 → 完整出處。改版時（例如 SFIA 9 → 10）只需要改這裡。
const COMPETENCY_SOURCES = {
  "ravi-mehta-12":     { label: "Ravi Mehta / Reforge Product Competency Model（12 competencies）", url: "https://www.ravi-mehta.com/product-manager-skills/", checkedAt: "2026-08-01" },
  "ispma-spm":         { label: "ISPMA SPM Framework（SPM Foundation Syllabus V.2.1）",             url: "https://ispma.org/bok/",                              checkedAt: "2026-08-01" },
  "svpg-assessment":   { label: "SVPG Coaching Tools: The Assessment（3 pillars / 13 criteria）",   url: "https://www.svpg.com/coaching-tools-the-assessment/",  checkedAt: "2026-08-01" },
  "product-compass-8": { label: "Product Compass PM Competence Map（8 categories）",                url: "https://www.productcompass.pm/p/your-pm-competence-map-skills-assessment", checkedAt: "2026-08-01" },
  "sfia-9-prod":       { label: "SFIA 9 — Product management (PROD)，定義於 level 2–6",             url: "https://sfia-online.org/en/sfia-9/skills/product-management", checkedAt: "2026-08-01", note: "SFIA 10 在 consultation，改版時這裡要更新" },
  "pmwheel":           { label: "Petra Wille PMwheel（8 dimensions）",                              url: "https://www.strongproductpeople.com/pmwheel",         checkedAt: "2026-08-01" },
};

const COMPETENCIES = [
  // ── Product Execution ─────────────────────────────────────────────
  {
    id: "feature-specification", area: "product-execution",
    name: "Feature Specification", nameZh: "需求規格",
    definition: "蒐集需求、定義功能、設定目標，並寫成清楚可執行的格式。",
    sources: ["ravi-mehta-12", "ispma-spm", "product-compass-8"],
  },
  {
    id: "product-delivery", area: "product-execution",
    name: "Product Delivery", nameZh: "產品交付",
    definition: "與工程、設計等直屬團隊緊密合作，快速且迭代地把功能交出去。",
    sources: ["ravi-mehta-12", "ispma-spm", "product-compass-8", "pmwheel"],
  },
  {
    id: "quality-assurance", area: "product-execution",
    name: "Quality Assurance", nameZh: "品質把關",
    definition: "找出、排序並解決技術、功能與商業面的品質問題。",
    sources: ["ravi-mehta-12", "sfia-9-prod"],
  },

  // ── Customer Insight ──────────────────────────────────────────────
  {
    id: "fluency-with-data", area: "customer-insight",
    name: "Fluency with Data", nameZh: "數據流暢度",
    definition: "用數據產生可行動的洞察，並用那些洞察達成目標。",
    sources: ["ravi-mehta-12", "svpg-assessment", "product-compass-8"],
  },
  {
    id: "voice-of-the-customer", area: "customer-insight",
    name: "Voice of the Customer", nameZh: "顧客之聲",
    definition: "運用各種形式的使用者回饋，理解使用者實際如何使用產品。",
    sources: ["ravi-mehta-12", "svpg-assessment", "product-compass-8", "ispma-spm", "pmwheel"],
  },
  {
    id: "ux-design", area: "customer-insight",
    name: "User Experience Design", nameZh: "使用者體驗設計",
    definition: "定義需求並產出好用的 UX 設計。",
    sources: ["ravi-mehta-12"],
  },

  // ── Product Strategy ──────────────────────────────────────────────
  {
    id: "business-outcome-ownership", area: "product-strategy",
    name: "Business Outcome Ownership", nameZh: "商業成果當責",
    definition: "把產品功能與目標連到商業成果，並對那個成果負責。",
    sources: ["ravi-mehta-12", "product-compass-8"],
  },
  {
    id: "vision-roadmapping", area: "product-strategy",
    name: "Product Vision & Roadmapping", nameZh: "產品願景與 Roadmap",
    definition: "為自己負責的範圍定義願景，並讓它連回公司策略。",
    sources: ["ravi-mehta-12", "ispma-spm", "sfia-9-prod", "pmwheel"],
  },
  {
    id: "strategic-impact", area: "product-strategy",
    name: "Strategic Impact", nameZh: "策略影響力",
    definition: "理解並實質貢獻於公司層級的商業策略。",
    sources: ["ravi-mehta-12", "ispma-spm", "sfia-9-prod"],
  },

  // ISPMA 補充：軟體產品特有，Ravi Mehta 的 12 項沒有對應。
  // 這 4 項是現有 SKILLS_DATA 的完全空白區。
  {
    id: "pricing-packaging", area: "product-strategy",
    name: "Pricing & Packaging", nameZh: "定價與方案設計",
    definition: "設計定價模型與方案分層，讓收費結構同時符合顧客價值與商業目標。",
    sources: ["ispma-spm", "product-compass-8"],
  },
  {
    id: "delivery-model", area: "product-strategy",
    name: "Delivery Model & Service Strategy", nameZh: "交付模式與服務策略",
    definition: "決定產品怎麼交付與怎麼被服務（雲端／地端、自助／導入、SLA 與支援層級）。",
    sources: ["ispma-spm"],
  },
  {
    id: "financial-management", area: "product-strategy",
    name: "Financial Management", nameZh: "產品財務管理",
    definition: "看懂並管理產品的損益：成本結構、單位經濟、投資回收。",
    sources: ["ispma-spm"],
  },
  {
    id: "ecosystem-management", area: "product-strategy",
    name: "Ecosystem Management", nameZh: "生態系管理",
    definition: "經營產品周邊的夥伴、整合與平台關係。",
    sources: ["ispma-spm"],
  },

  // ── Influencing People ────────────────────────────────────────────
  {
    id: "stakeholder-management", area: "influencing-people",
    name: "Stakeholder Management", nameZh: "利害關係人管理",
    definition: "主動辨識受自己負責範圍影響的利害關係人，並建立共識。",
    sources: ["ravi-mehta-12", "svpg-assessment", "product-compass-8"],
  },
  {
    id: "team-leadership", area: "influencing-people",
    name: "Team Leadership", nameZh: "團隊領導",
    definition: "管理與輔導直屬部屬，讓他們能自己把事情做成。",
    sources: ["ravi-mehta-12", "svpg-assessment", "pmwheel"],
  },
  {
    id: "managing-up", area: "influencing-people",
    name: "Managing Up", nameZh: "向上管理",
    definition: "借助資深主管與高層的力量來達成目標。",
    sources: ["ravi-mehta-12"],
  },
];

// 給 rubric 用的合法值域檢查。Phase 2 的 validate-data.mjs 會用同一份。

const COMPETENCY_IDS = COMPETENCIES.map(c => c.id);

// ── ITEMS：可評估的項目 ────────────────────────────────────────────────
//
// kind 的判準是**能不能指出一件具體的產出物來證明它**（也就是 eval 欄位）：
//
//   skill    能用產出物證明的能力。給分，要有 eval
//   topic    概念知識。讀過就是讀過，沒有產出物可交，**不給分**
//   ability  要靠實作 + 反思養成的（溝通、衝突處理、影響力）。**刻意不給 0–10 分**，
//            證據型態是反思紀錄。來源見 framework.md §二 ③（SSIR 的 skills / abilities 二分）
//   tool     軟體熟練度。會用就是會用，不是能力
//
// 把 topic 與 tool 分出來的實際效果：可評分的集合從 131 縮到 76 項 skill。
// 「讀過 What is Product Management?」本來就不該和「做得出一份過 rubric 的 PRD」
// 佔同一格分數。
//
// packaged: false = 不隨框架打包（求職材料，不是產品能力）。站上照樣顯示。
// l1 = 掛在哪個 L1 competency。topic / tool 可以是 null。
// cat = Product Compass 分類，技能圖譜的雷達軸用它。只有原本在 SKILLS_DATA 的項目有。
//
// ⚠️ 目前 51 項 skill 的 eval 還是 null。**要打包給別人之前得補完**——
//    eval 是這個框架真正的價值，空白的 eval 等於送一張空表格。
const ITEMS = [
  { id: "what-is-product-management", kind: "topic", l1: null, cat: null, priority: null,
    name: "What is Product Management?",
    eval: null },
  { id: "product-vs-project-management", kind: "topic", l1: null, cat: null, priority: null,
    name: "Product vs Project Management",
    eval: null },
  { id: "roles-and-responsibilities", kind: "topic", l1: null, cat: null, priority: null,
    name: "Roles & Responsibilities",
    eval: null },
  { id: "key-skills-overview", kind: "topic", l1: null, cat: null, priority: null,
    name: "Key Skills Overview",
    eval: null },
  { id: "mind-mapping", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Mind Mapping",
    eval: null },
  { id: "brainstorming", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Brainstorming",
    eval: null },
  { id: "scamper", kind: "topic", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "SCAMPER",
    eval: null },
  { id: "problem-framing", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Problem Framing",
    eval: null },
  { id: "blue-ocean-strategy", kind: "topic", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Blue Ocean Strategy",
    eval: null },
  { id: "triz", kind: "topic", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "TRIZ",
    eval: null },
  { id: "identifying-market-needs", kind: "topic", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Identifying Market Needs",
    eval: null },
  { id: "competitive-analysis", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Competitive Analysis",
    eval: null },
  { id: "emerging-market-trends", kind: "topic", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Emerging Market Trends",
    eval: null },
  { id: "tam-sam-som", kind: "skill", l1: "strategic-impact", cat: null, priority: null,
    name: "TAM / SAM / SOM",
    eval: null },
  { id: "user-personas", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "User Personas",
    eval: null },
  { id: "user-interviews", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "User Interviews",
    eval: null },
  { id: "surveys-and-questionnaires", kind: "skill", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Surveys & Questionnaires",
    eval: null },
  { id: "ethnographic-research", kind: "topic", l1: "voice-of-the-customer", cat: null, priority: null,
    name: "Ethnographic Research",
    eval: null },
  { id: "jobs-to-be-done", kind: "skill", l1: "voice-of-the-customer", cat: "產品發現", priority: 75, aliases: ["Jobs to Be Done (JTBD)"],
    name: "Jobs to Be Done（JTBD）",
    eval: "為一個產品寫 5 個 JTBD Job Statement（When [situation], I want to [goal], so I can [outcome]），附用戶研究依據" },
  { id: "usability-testing", kind: "skill", l1: "quality-assurance", cat: "產品發現", priority: 65,
    name: "Usability Testing",
    eval: "用 Figma prototype 對 5 名目標用戶做 Think-Aloud test，輸出任務成功率 + 錯誤類型 + Severity Rating（Nielsen 1~4 分）" },
  { id: "usp-positioning", kind: "skill", l1: "business-outcome-ownership", cat: null, priority: null,
    name: "USP / Positioning",
    eval: null },
  { id: "market-segmentation", kind: "skill", l1: "business-outcome-ownership", cat: null, priority: null,
    name: "Market Segmentation",
    eval: null },
  { id: "value-proposition-canvas", kind: "skill", l1: "strategic-impact", cat: null, priority: null,
    name: "Value Proposition Canvas",
    eval: null },
  { id: "business-model-canvas", kind: "skill", l1: "financial-management", cat: "商業與策略", priority: 55,
    name: "Business Model Canvas",
    eval: "對一個真實產品填完整 Strategyzer BMC，配合競品做對比，放作品集" },
  { id: "porter-s-five-forces", kind: "topic", l1: "strategic-impact", cat: "商業與策略", priority: 40, aliases: ["Five Forces Analysis"],
    name: "Porter's Five Forces",
    eval: null },
  { id: "swot-pestle", kind: "topic", l1: "strategic-impact", cat: null, priority: null,
    name: "SWOT / PESTLE",
    eval: null },
  { id: "competitive-advantage", kind: "topic", l1: "strategic-impact", cat: null, priority: null,
    name: "Competitive Advantage",
    eval: null },
  { id: "strategic-thinking", kind: "topic", l1: "strategic-impact", cat: null, priority: null,
    name: "Strategic Thinking",
    eval: null },
  { id: "okrs", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "OKRs",
    eval: null },
  { id: "north-star-metric", kind: "skill", l1: "fluency-with-data", cat: "數據分析", priority: 80,
    name: "North Star Metric",
    eval: "為一個真實產品定義 NSM，並畫出完整 Input Metrics Tree（3 層），說明每層指標與 NSM 的關係，以 1 頁文件呈現" },
  { id: "goal-types-and-baselines", kind: "topic", l1: "vision-roadmapping", cat: null, priority: null,
    name: "Goal Types & Baselines",
    eval: null },
  { id: "product-vision-statement", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "Product Vision Statement",
    eval: null },
  { id: "creating-a-roadmap", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "Creating a Roadmap",
    eval: null },
  { id: "prioritizing-features", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "Prioritizing Features",
    eval: null },
  { id: "rice-moscow", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "RICE / MoSCoW",
    eval: null },
  { id: "outcome-based-roadmaps", kind: "topic", l1: "feature-specification", cat: null, priority: null,
    name: "Outcome-Based Roadmaps",
    eval: null },
  { id: "communicating-the-roadmap", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "Communicating the Roadmap",
    eval: null },
  { id: "writing-prds", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "Writing PRDs",
    eval: null },
  { id: "user-stories", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "User Stories",
    eval: null },
  { id: "job-stories", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "Job Stories",
    eval: null },
  { id: "acceptance-criteria", kind: "skill", l1: "quality-assurance", cat: null, priority: null,
    name: "Acceptance Criteria",
    eval: null },
  { id: "backlog-management", kind: "skill", l1: "vision-roadmapping", cat: null, priority: null,
    name: "Backlog Management",
    eval: null },
  { id: "user-story-mapping", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "User Story Mapping",
    eval: null },
  { id: "principles-of-ux-design", kind: "topic", l1: "ux-design", cat: null, priority: null,
    name: "Principles of UX Design",
    eval: null },
  { id: "wireframing-and-prototyping", kind: "skill", l1: "ux-design", cat: null, priority: null,
    name: "Wireframing & Prototyping",
    eval: null },
  { id: "design-thinking", kind: "skill", l1: "ux-design", cat: null, priority: null,
    name: "Design Thinking",
    eval: null },
  { id: "service-design", kind: "skill", l1: "ux-design", cat: "產品發現", priority: 55,
    name: "Service Design",
    eval: "對一個社會議題用 Service Blueprint 呈現前後台流程與接觸點，識別 2~3 個痛點改善機會，以圖表輸出" },
  { id: "interaction-design", kind: "skill", l1: "ux-design", cat: null, priority: null,
    name: "Interaction Design",
    eval: null },
  { id: "a-b-testing", kind: "skill", l1: "quality-assurance", cat: null, priority: null,
    name: "A/B Testing",
    eval: null },
  { id: "scrum", kind: "skill", l1: "delivery-model", cat: null, priority: null,
    name: "Scrum",
    eval: null },
  { id: "kanban", kind: "skill", l1: "delivery-model", cat: null, priority: null,
    name: "Kanban",
    eval: null },
  { id: "sprint-planning", kind: "skill", l1: "delivery-model", cat: null, priority: null,
    name: "Sprint Planning",
    eval: null },
  { id: "daily-standups", kind: "skill", l1: "delivery-model", cat: null, priority: null,
    name: "Daily Standups",
    eval: null },
  { id: "retrospectives", kind: "skill", l1: "delivery-model", cat: null, priority: null,
    name: "Retrospectives",
    eval: null },
  { id: "mvp", kind: "skill", l1: "delivery-model", cat: null, priority: null,
    name: "MVP",
    eval: null },
  { id: "go-to-market-strategy", kind: "skill", l1: "business-outcome-ownership", cat: null, priority: null,
    name: "Go-to-Market Strategy",
    eval: null },
  { id: "release-strategies", kind: "topic", l1: "product-delivery", cat: null, priority: null,
    name: "Release Strategies",
    eval: null },
  { id: "feature-toggles-dark-launch", kind: "topic", l1: "product-delivery", cat: null, priority: null,
    name: "Feature Toggles / Dark Launch",
    eval: null },
  { id: "growth-hacking", kind: "topic", l1: "product-delivery", cat: null, priority: null,
    name: "Growth Hacking",
    eval: null },
  { id: "dau-mau", kind: "topic", l1: "fluency-with-data", cat: null, priority: null,
    name: "DAU / MAU",
    eval: null },
  { id: "retention-rate", kind: "topic", l1: "fluency-with-data", cat: null, priority: null,
    name: "Retention Rate",
    eval: null },
  { id: "churn-rate", kind: "topic", l1: "fluency-with-data", cat: null, priority: null,
    name: "Churn Rate",
    eval: null },
  { id: "conversion-rate", kind: "topic", l1: "fluency-with-data", cat: null, priority: null,
    name: "Conversion Rate",
    eval: null },
  { id: "ltv-cac", kind: "topic", l1: "financial-management", cat: null, priority: null,
    name: "LTV / CAC",
    eval: null },
  { id: "funnel-analysis", kind: "skill", l1: "fluency-with-data", cat: null, priority: null,
    name: "Funnel Analysis",
    eval: null },
  { id: "cohort-analysis", kind: "skill", l1: "fluency-with-data", cat: null, priority: null,
    name: "Cohort Analysis",
    eval: null },
  { id: "ga4-mixpanel", kind: "skill", l1: "fluency-with-data", cat: null, priority: null,
    name: "GA4 / Mixpanel",
    eval: null },
  { id: "sql-for-product", kind: "skill", l1: "fluency-with-data", cat: null, priority: null,
    name: "SQL for Product",
    eval: null },
  { id: "active-listening", kind: "ability", l1: "stakeholder-management", cat: null, priority: null,
    name: "Active Listening",
    eval: null },
  { id: "conflict-resolution", kind: "ability", l1: "stakeholder-management", cat: "人員領導", priority: 75,
    name: "Conflict Resolution",
    eval: null },
  { id: "alignment-and-buy-in", kind: "ability", l1: "stakeholder-management", cat: null, priority: null,
    name: "Alignment & Buy-In",
    eval: null },
  { id: "difficult-conversations", kind: "ability", l1: "stakeholder-management", cat: null, priority: null,
    name: "Difficult Conversations",
    eval: null },
  { id: "executive-communication", kind: "ability", l1: "managing-up", cat: "人員領導", priority: 70,
    name: "Executive Communication",
    eval: "寫一份 1-page Executive Brief（BLUF 格式：結論先行 → 背景 → 選項 → 建議 → 所需決策），模擬向 C-level 報告" },
  { id: "jira-gitlab", kind: "tool", l1: null, cat: null, priority: null,
    name: "Jira / GitLab",
    eval: null },
  { id: "notion", kind: "tool", l1: null, cat: null, priority: null,
    name: "Notion",
    eval: null },
  { id: "linear", kind: "tool", l1: null, cat: null, priority: null,
    name: "Linear",
    eval: null },
  { id: "slack", kind: "tool", l1: null, cat: null, priority: null,
    name: "Slack",
    eval: null },
  { id: "figma", kind: "tool", l1: null, cat: null, priority: null,
    name: "Figma（讀稿）",
    eval: null },
  { id: "productboard-aha", kind: "tool", l1: null, cat: null, priority: null,
    name: "ProductBoard / Aha",
    eval: null },
  { id: "amplitude-heap", kind: "tool", l1: null, cat: null, priority: null,
    name: "Amplitude / Heap",
    eval: null },
  { id: "miro-figjam", kind: "tool", l1: null, cat: null, priority: null,
    name: "Miro / FigJam（workshop）",
    eval: null },
  { id: "ai-feature-design", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "AI Feature Design",
    eval: null },
  { id: "prompt-engineering", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "Prompt Engineering",
    eval: null },
  { id: "model-limitation-評估", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "Model Limitation 評估",
    eval: null },
  { id: "ml-in-product-mgmt", kind: "topic", l1: "feature-specification", cat: null, priority: null,
    name: "ML in Product Mgmt",
    eval: null },
  { id: "ai-風險評估", kind: "skill", l1: "feature-specification", cat: null, priority: null,
    name: "AI 風險評估",
    eval: null },
  { id: "platform-thinking", kind: "topic", l1: "feature-specification", cat: null, priority: null,
    name: "Platform Thinking",
    eval: null },
  { id: "scaling-products", kind: "topic", l1: "feature-specification", cat: null, priority: null,
    name: "Scaling Products",
    eval: null },
  { id: "influencing-without-authority", kind: "ability", l1: "managing-up", cat: null, priority: null,
    name: "Influencing Without Authority",
    eval: null },
  { id: "emotional-intelligence", kind: "ability", l1: "team-leadership", cat: null, priority: null,
    name: "Emotional Intelligence",
    eval: null },
  { id: "市場規模評估", kind: "skill", l1: "strategic-impact", cat: "商業與策略", priority: 60,
    name: "市場規模評估（TAM/SAM/SOM）",
    eval: "用公開資料計算一個市場的 TAM/SAM/SOM，附假設來源，以 1 頁簡報呈現" },
  { id: "競品分析", kind: "skill", l1: "strategic-impact", cat: "商業與策略", priority: 80,
    name: "競品分析",
    eval: "選 4~6 家競品、定義 8~10 個比較維度（功能/定價/GTM/壁壘），輸出競品矩陣 + Positioning Map" },
  { id: "okr-設定", kind: "skill", l1: "product-delivery", cat: "執行力", priority: 90,
    name: "OKR 設定",
    eval: null },
  { id: "rice-moscow-優先序", kind: "skill", l1: "product-delivery", cat: "執行力", priority: 85,
    name: "RICE / MoSCoW 優先序",
    eval: "對真實 Backlog（≥10 項）做 RICE 評分，附每個假設的來源（訪談/數據/商業目標），以 Google Sheets 呈現" },
  { id: "prd-撰寫", kind: "skill", l1: "product-delivery", cat: "執行力", priority: 95,
    name: "PRD 撰寫",
    eval: "寫完整 PRD（問題陳述 + 使用者故事 + 驗收標準 + 成功指標 + 邊界條件），公開發布在 Notion，可作為帶回家作業範本" },
  { id: "agile-scrum", kind: "skill", l1: "product-delivery", cat: "執行力", priority: 95,
    name: "Agile / Scrum",
    eval: null },
  { id: "risk-management", kind: "skill", l1: "product-delivery", cat: "執行力", priority: 45,
    name: "Risk Management",
    eval: "建立 RAID Log + 機率/影響矩陣，提出 Top 5 風險緩解計畫；Google PM Certificate（Coursera）可作憑證" },
  { id: "跨部門溝通", kind: "ability", l1: "stakeholder-management", cat: "人員領導", priority: 90,
    name: "跨部門溝通",
    eval: null },
  { id: "stakeholder-alignment", kind: "ability", l1: "stakeholder-management", cat: "人員領導", priority: 90,
    name: "Stakeholder Alignment",
    eval: null },
  { id: "ga4-分析工具", kind: "skill", l1: "fluency-with-data", cat: "數據分析", priority: 90,
    name: "GA4 / 分析工具",
    eval: "完成 Google Skillshop GA4 Certification（免費，~4~6h，頒發可分享 badge，可直接列履歷）" },
  { id: "sql", kind: "skill", l1: "fluency-with-data", cat: "數據分析", priority: 85,
    name: "SQL（Product Analytics）",
    eval: "在 StrataScratch 完成 30 題 PM/Data 等級 SQL 題；用 BigQuery 公開資料集產出一份 Retention 分析放作品集" },
  { id: "funnel-cohort-分析", kind: "skill", l1: "fluency-with-data", cat: "數據分析", priority: 85,
    name: "Funnel / Cohort 分析",
    eval: "用 Kaggle 電商公開資料集做完整留存曲線 + Funnel 分析，輸出帶結論的圖表報告（SQL + 圖），放作品集" },
  { id: "a-b-testing-設計", kind: "skill", l1: "fluency-with-data", cat: "數據分析", priority: 70,
    name: "A/B Testing 設計",
    eval: "寫 A/B Test Design Doc：假設 → 組別定義 → Primary metric + Guardrail → 樣本數計算（Evan Miller）→ 決策標準" },
  { id: "user-interview-設計", kind: "skill", l1: "voice-of-the-customer", cat: "產品發現", priority: 80,
    name: "User Interview 設計",
    eval: "完成 5 次使用者訪談 → 輸出逐字稿 + Affinity Diagram + ≥3 個洞察報告，放作品集（參考《The Mom Test》避免引導性問題）" },
  { id: "problem-definition", kind: "skill", l1: "voice-of-the-customer", cat: "產品發現", priority: 90,
    name: "Problem Definition",
    eval: null },
  { id: "mvp-定義", kind: "skill", l1: "fluency-with-data", cat: "實驗驗證", priority: 85,
    name: "MVP 定義",
    eval: "寫 MVP Scoping 案例文件：列入選/排除功能 + 理由 + 驗證 MVP 成功的最低指標，以 Notion 頁面呈現放作品集" },
  { id: "a-b-testing-執行", kind: "skill", l1: "fluency-with-data", cat: "實驗驗證", priority: 70,
    name: "A/B Testing 執行",
    eval: "用 GrowthBook（免費開源）在 side project 實際設定一個 experiment flag，截圖紀錄設定流程與結果分析，放作品集" },
  { id: "假型-測試", kind: "skill", l1: "fluency-with-data", cat: "實驗驗證", priority: 50,
    name: "假型（Fake Door）測試",
    eval: null },
  { id: "gtm-strategy", kind: "skill", l1: "business-outcome-ownership", cat: "產品行銷", priority: 60,
    name: "GTM Strategy",
    eval: "寫 GTM Plan 文件：ICP 定義 → 定價策略 → 行銷通路 → 銷售動作 → 上市時程 → 成功指標（1 頁內最佳）" },
  { id: "value-proposition-設計", kind: "skill", l1: "business-outcome-ownership", cat: "產品行銷", priority: 70,
    name: "Value Proposition 設計",
    eval: "完成 Strategyzer Value Proposition Canvas：Customer Jobs/Pains/Gains ≥5 項，對應 Pain Relievers/Gain Creators，圖文並茂放作品集" },
  { id: "launch-planning", kind: "skill", l1: "business-outcome-ownership", cat: "產品行銷", priority: 65,
    name: "Launch Planning",
    eval: "撰寫產品上市計畫：目標 → 時程 → 溝通計畫 → 成功指標，含 RACI chart，以 1~2 頁文件呈現放作品集" },
  { id: "api-系統架構溝通", kind: "skill", l1: "product-delivery", cat: "技術能力", priority: 95,
    name: "API / 系統架構溝通",
    eval: null },
  { id: "前端可行性評估", kind: "skill", l1: "product-delivery", cat: "技術能力", priority: 90,
    name: "前端可行性評估",
    eval: null },
  { id: "後端-db-邏輯理解", kind: "skill", l1: "product-delivery", cat: "技術能力", priority: 85,
    name: "後端 / DB 邏輯理解",
    eval: null },
  { id: "figma-讀稿-基礎操作", kind: "skill", l1: "product-delivery", cat: "技術能力", priority: 80,
    name: "Figma 讀稿 / 基礎操作",
    eval: null },
  { id: "rag-知識庫治理", kind: "skill", l1: "feature-specification", cat: "AI-Native PM", priority: 70,
    name: "RAG 知識庫治理",
    eval: "設計一個 RAG 系統的資料品質審核 checklist + 回答品質評估框架（RAGAS 或自訂指標），以文件形式呈現" },
  { id: "ai-輔助-discovery-的證據紀律", kind: "skill", l1: "feature-specification", cat: "AI-Native PM", priority: 80,
    name: "AI 輔助 discovery 的證據紀律",
    eval: "完成一次 AI 輔助 discovery 報告，明確標記哪些 insight 來自真實用戶訪談、哪些來自模型推論，呈現方法論" },
  { id: "vibe-coding-prototype", kind: "skill", l1: "feature-specification", cat: "AI-Native PM", priority: 85,
    name: "vibe-coding prototype",
    eval: null },
  { id: "agent-工作流設計", kind: "skill", l1: "feature-specification", cat: "AI-Native PM", priority: 75,
    name: "Agent 工作流設計",
    eval: "設計並實作一個 3 步驟以上的 agent workflow，記錄工具邊界、人工介入點、失敗回復機制，以流程圖+說明文件呈現" },
  { id: "why-pm-why-now-why-you-敘事", kind: "skill", l1: null, cat: "轉職敘事", priority: 95, packaged: false,
    name: "Why PM / Why now / Why you 敘事",
    eval: "寫出並練習一個 90 秒版本的 PM 轉職故事，涵蓋 why PM/why now/why you，請 2 人以上提供回饋並迭代" },
  { id: "star-故事庫", kind: "skill", l1: null, cat: "轉職敘事", priority: 90, packaged: false,
    name: "STAR 故事庫（3–5 則）",
    eval: "整理 3~5 則 STAR 格式的職涯故事（含社創經驗），每則含 PM 能力連結，備好面試即取用的 Notion 頁面" },
];

// ── CURRICULUM：學習路徑結構（沿用 roadmap.sh 的 12 個 phase）───────────
//
// 只存「哪個 phase 的哪個 group 教哪些 item」，**不存狀態**。
// 同一個 itemId 可以出現在兩個 phase——North Star Metric 在 Vision & Goals 與
// Product Metrics 都出現，那是課程結構的事實，不是重複資料。
const CURRICULUM = [
  { phase: 1, title: "Introduction", icon: "📌", color: "#6366f1", groups: [
    { name: "基礎概念", items: [
      { id: "what-is-product-management", name: "What is Product Management?" },
      { id: "product-vs-project-management", name: "Product vs Project Management" },
      { id: "roles-and-responsibilities", name: "Roles & Responsibilities" },
      { id: "key-skills-overview", name: "Key Skills Overview" },
    ]},
  ]},
  { phase: 2, title: "Idea Generation", icon: "💡", color: "#0891b2", groups: [
    { name: "發想工具", items: [
      { id: "mind-mapping", name: "Mind Mapping" },
      { id: "brainstorming", name: "Brainstorming" },
      { id: "scamper", name: "SCAMPER" },
      { id: "problem-framing", name: "Problem Framing" },
      { id: "blue-ocean-strategy", name: "Blue Ocean Strategy" },
      { id: "triz", name: "TRIZ" },
    ]},
  ]},
  { phase: 3, title: "Market & User Research", icon: "🔍", color: "#059669", groups: [
    { name: "市場分析", items: [
      { id: "identifying-market-needs", name: "Identifying Market Needs" },
      { id: "competitive-analysis", name: "Competitive Analysis" },
      { id: "emerging-market-trends", name: "Emerging Market Trends" },
      { id: "tam-sam-som", name: "TAM / SAM / SOM" },
    ]},
    { name: "用戶研究", items: [
      { id: "user-personas", name: "User Personas" },
      { id: "user-interviews", name: "User Interviews" },
      { id: "surveys-and-questionnaires", name: "Surveys & Questionnaires" },
      { id: "ethnographic-research", name: "Ethnographic Research" },
      { id: "jobs-to-be-done", name: "Jobs to Be Done (JTBD)" },
      { id: "usability-testing", name: "Usability Testing" },
    ]},
  ]},
  { phase: 4, title: "Product Strategy", icon: "🎯", color: "#d97706", groups: [
    { name: "定位", items: [
      { id: "usp-positioning", name: "USP / Positioning" },
      { id: "market-segmentation", name: "Market Segmentation" },
      { id: "value-proposition-canvas", name: "Value Proposition Canvas" },
      { id: "business-model-canvas", name: "Business Model Canvas" },
    ]},
    { name: "策略", items: [
      { id: "porter-s-five-forces", name: "Five Forces Analysis" },
      { id: "swot-pestle", name: "SWOT / PESTLE" },
      { id: "competitive-advantage", name: "Competitive Advantage" },
      { id: "strategic-thinking", name: "Strategic Thinking" },
    ]},
  ]},
  { phase: 5, title: "Vision & Goals", icon: "🌟", color: "#7c3aed", groups: [
    { name: "目標設定", items: [
      { id: "okrs", name: "OKRs" },
      { id: "north-star-metric", name: "North Star Metric" },
      { id: "goal-types-and-baselines", name: "Goal Types & Baselines" },
      { id: "product-vision-statement", name: "Product Vision Statement" },
    ]},
  ]},
  { phase: 6, title: "Product Planning", icon: "📋", color: "#db2777", groups: [
    { name: "Roadmap", items: [
      { id: "creating-a-roadmap", name: "Creating a Roadmap" },
      { id: "prioritizing-features", name: "Prioritizing Features" },
      { id: "rice-moscow", name: "RICE / MoSCoW" },
      { id: "outcome-based-roadmaps", name: "Outcome-Based Roadmaps" },
      { id: "communicating-the-roadmap", name: "Communicating the Roadmap" },
    ]},
    { name: "需求", items: [
      { id: "writing-prds", name: "Writing PRDs" },
      { id: "user-stories", name: "User Stories" },
      { id: "job-stories", name: "Job Stories" },
      { id: "acceptance-criteria", name: "Acceptance Criteria" },
      { id: "backlog-management", name: "Backlog Management" },
      { id: "user-story-mapping", name: "User Story Mapping" },
    ]},
  ]},
  { phase: 7, title: "Product Design", icon: "🎨", color: "#0891b2", groups: [
    { name: "UX/UI", items: [
      { id: "principles-of-ux-design", name: "Principles of UX Design" },
      { id: "wireframing-and-prototyping", name: "Wireframing & Prototyping" },
      { id: "design-thinking", name: "Design Thinking" },
      { id: "service-design", name: "Service Design" },
      { id: "interaction-design", name: "Interaction Design" },
      { id: "a-b-testing", name: "A/B Testing" },
    ]},
  ]},
  { phase: 8, title: "Development & Launch", icon: "🚀", color: "#059669", groups: [
    { name: "Agile", items: [
      { id: "scrum", name: "Scrum" },
      { id: "kanban", name: "Kanban" },
      { id: "sprint-planning", name: "Sprint Planning" },
      { id: "daily-standups", name: "Daily Standups" },
      { id: "retrospectives", name: "Retrospectives" },
      { id: "mvp", name: "MVP" },
    ]},
    { name: "上市", items: [
      { id: "go-to-market-strategy", name: "Go-to-Market Strategy" },
      { id: "release-strategies", name: "Release Strategies" },
      { id: "feature-toggles-dark-launch", name: "Feature Toggles / Dark Launch" },
      { id: "growth-hacking", name: "Growth Hacking" },
    ]},
  ]},
  { phase: 9, title: "Product Metrics", icon: "📊", color: "#d97706", groups: [
    { name: "核心指標", items: [
      { id: "dau-mau", name: "DAU / MAU" },
      { id: "retention-rate", name: "Retention Rate" },
      { id: "churn-rate", name: "Churn Rate" },
      { id: "conversion-rate", name: "Conversion Rate" },
      { id: "ltv-cac", name: "LTV / CAC" },
      { id: "north-star-metric", name: "North Star Metric" },
    ]},
    { name: "數據分析", items: [
      { id: "funnel-analysis", name: "Funnel Analysis" },
      { id: "cohort-analysis", name: "Cohort Analysis" },
      { id: "ga4-mixpanel", name: "GA4 / Mixpanel" },
      { id: "sql-for-product", name: "SQL for Product" },
      { id: "a-b-testing", name: "A/B Testing" },
    ]},
  ]},
  { phase: 10, title: "Stakeholder Management", icon: "🤝", color: "#dc2626", groups: [
    { name: "溝通", items: [
      { id: "active-listening", name: "Active Listening" },
      { id: "conflict-resolution", name: "Conflict Resolution" },
      { id: "alignment-and-buy-in", name: "Alignment & Buy-In" },
      { id: "difficult-conversations", name: "Difficult Conversations" },
      { id: "executive-communication", name: "Executive Communication" },
    ]},
  ]},
  { phase: 11, title: "PM Tools", icon: "🛠", color: "#4f46e5", groups: [
    { name: "已熟悉", items: [
      { id: "jira-gitlab", name: "Jira / GitLab" },
      { id: "notion", name: "Notion" },
      { id: "linear", name: "Linear" },
      { id: "slack", name: "Slack" },
      { id: "figma", name: "Figma（讀稿）" },
    ]},
    { name: "待學", items: [
      { id: "productboard-aha", name: "ProductBoard / Aha" },
      { id: "amplitude-heap", name: "Amplitude / Heap" },
      { id: "miro-figjam", name: "Miro / FigJam（workshop）" },
    ]},
  ]},
  { phase: 12, title: "Advanced / AI PM", icon: "🤖", color: "#7c3aed", groups: [
    { name: "AI 相關", items: [
      { id: "ai-feature-design", name: "AI Feature Design" },
      { id: "prompt-engineering", name: "Prompt Engineering" },
      { id: "model-limitation-評估", name: "Model Limitation 評估" },
      { id: "ml-in-product-mgmt", name: "ML in Product Mgmt" },
      { id: "ai-風險評估", name: "AI 風險評估" },
    ]},
    { name: "高階技能", items: [
      { id: "platform-thinking", name: "Platform Thinking" },
      { id: "scaling-products", name: "Scaling Products" },
      { id: "influencing-without-authority", name: "Influencing Without Authority" },
      { id: "emotional-intelligence", name: "Emotional Intelligence" },
    ]},
  ]},
];

// ── 衍生視圖（render 時算，不存）──────────────────────────────────────
// 兩個函式都需要 ASSESSMENT（profile/assessment.js）。載入順序：competencies 先。

// 取代原本的 SKILLS_DATA：扁平技能表，餵技能圖譜的三個 sub-view。
// 只回傳有 cat 的項目，所以輸出與合併前的 39 項逐項相同。
function skillsView(assessment) {
  return ITEMS.filter(i => i.cat).map(i => ({
    id: i.id, cat: i.cat, skill: i.name, priority: i.priority, eval: i.eval,
    kind: i.kind, l1: i.l1,
    ...(assessment[i.id] || { status: 'need', reason: null, note: null, social: null, evidence: [] }),
  }));
}

// 取代原本的 ROADMAP_DATA：12 個 phase 的巢狀結構，餵能力地圖。
function roadmapView(assessment) {
  const byId = new Map(ITEMS.map(i => [i.id, i]));
  return CURRICULUM.map(p => ({
    title: p.title, icon: p.icon, color: p.color,
    groups: p.groups.map(g => ({
      name: g.name,
      // name 用 placement 自己的（roadmap.sh 原文）；status 從 assessment 翻回
      // 能力地圖的字彙：canonical 的 partial 在這裡叫 learning。
      skills: g.items.map(p => {
        const a = assessment[p.id] || {};
        const st = a.status === 'partial' ? 'learning' : (a.status || 'need');
        return { name: p.name, status: st, reason: a.reason || undefined };
      }),
    })),
  }));
}
